services:
    postgres_database:
        image: postgres:16
        environment:
            POSTGRES_USER: repo
            POSTGRES_PASSWORD: repo
            POSTGRES_DB: repo_${NODE_ENV}
        ports:
            - "5432:5432"
        volumes:
            - repo_postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U repo"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    repo_postgres_data:
        driver: local